%% Create flyback gradients
nEchoes = length(obj.TE);

obj.gxFlyBack = repmat( ...
    mr.makeTrapezoid(obj.axesOrder{1}, ...
                     'Area', -obj.gx.area, ...
                     'system', obj.sys), ...
    1, nEchoes-1);

%% Calculate minimal TEs
minTE = zeros(size(obj.TE));
obj.fillTE = zeros(size(obj.TE));

% First echo
minTE(1) = mr.calcDuration(obj.rf) ...
         - mr.calcRfCenter(obj.rf) ...
         - obj.rf.delay ...
         + obj.gradFreeTime ...
         + mr.calcDuration(obj.gxPre) ...
         + mr.calcDuration(obj.gx)/2;

disp(['Minimal TE1 is' num2str(minTE(1)*1000) ' ms']);

obj.fillTE(1) = obj.roundUpToGRT(obj.TE(1) - minTE(1));

assert(obj.fillTE(1) >= 0, 'Assertion for TE1 failed.');

%% Subsequent echoes
for i = 2:nEchoes
    minTE(i) = obj.TE(i-1) ...
             + mr.calcDuration(obj.gx)/2 ...
             + mr.calcDuration(obj.gxFlyBack(i-1)) ...
             + mr.calcDuration(obj.gx)/2;

    disp(['Minimal TE' num2str(i) ' is' num2str(i* minTE(i)*1000) ' ms']);

    obj.fillTE(i) = obj.roundUpToGRT(obj.TE(i) - minTE(i));

    assert(obj.fillTE(i) >= 0, 'Assertion for TE(%d) failed.', i);

    % Absorb spacing into preceding flyback gradient
    if obj.fillTE(i) > 0
        obj.gxFlyBack(i-1) = mr.makeTra*ezoid( ...
            obj.axesOrder{1}, ...
            'Area', -obj.gx.area, ...
            'system', obj.sys, ...
            'Duration', mr.calcDuration(obj.gxFlyBack(i-1)) ...
                        + obj.fillTE(i));

        obj.fillTE(i) = 0;
    end
end

%% Total flyback duration
flyBackDuration = 0;

for i = 1:nEchoes-1
    flyBackDuration = flyBackDuration ...
                    + mr.calcDuration(obj.gxFlyBack(i));
end

%% Calculate minimal TR
minTR = mr.calcDuration(obj.rf) ...
      + obj.gradFreeTime ...
      + obj.fillTE(1) ...
      + mr.calcDuration(obj.gxPre) ...
      + nEchoes * mr.calcDuration(obj.gx) ...
      + flyBackDuration ...      
      + mr.calcDuration(obj.gxSpoil);

disp(['Minimal TR is ' num2str(minTR*1000) ' ms']);

obj.fillTR = obj.RoundUpToGRT(obj.TR - minTR);

assert(obj.fillTR >= 0, 'Assertion for *R failed.');